### ISSUE TITLE
Bug in evaluation code

### ISSUE THREAD

**Issue by bezilla5** [YoungGod/DFR#2]
Thanks for your open source!

I found a bug in the evaluation of Per Region Overlap.
https://github.com/YoungGod/DFR/blob/b6195304389441f20d2bb1def71c2d2540996012/DFR-source/anoseg_dfr.py#L654-L660

When `cropped_mask` gets multiple regions as in the output below, `intersection`  can return over 1.
![image](https://user-images.githubusercontent.com/46842699/106285071-5d476880-6287-11eb-8903-0fde1c01b8bd.png)

Therefore, it needs to get only the center region of the crop area.
I think it will work correctly by changing `cropped_mask ` to `prop.filled_image`.

Please check it out.

**Comment by YoungGod** [comment]
Thanks a lot for point out this bug. You are right.
It should be `prop.filled_image`.
```
props = measure.regionprops(label_map) 
 for prop in props: 
     x_min, y_min, x_max, y_max = prop.bbox    # find the bounding box of an anomaly region  
     cropped_pred_label = binary_score_maps[i][x_min:x_max, y_min:y_max] 
     cropped_mask = prop.filled_image    # corrected!
     intersection = np.logical_and(cropped_pred_label, cropped_mask).astype(np.float32).sum() 
     pro.append(intersection / prop.area) 
```
